exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprctl setcursor Bibata-Modern-Ice 26
exec-once =  vicinae server --replace
exec-once = hyprmon --profile LAPTOP_ONLY
# exec-once = ~/.config/hypr/scripts/monitor-failsafe.sh
exec-once = dms run