exec-once = bash -c "wl-paste --watch cliphist store &"
exec-once = hyprctl setcursor Bibata-Modern-Ice 26
exec-once =  vicinae server
exec-once = hyprmon --profile LAPTOP_ONLY
# exec-once = ~/.config/hypr/scripts/monitor-failsafe.sh