-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(4385be)",
			inactive_border = "rgb(575653)",
		},
	},
	group = {
		col = {
			border_active = "rgb(4385be)",
			border_inactive = "rgb(575653)",
			border_locked_active = "rgb(d14d41)",
			border_locked_inactive = "rgb(575653)",
		},
		groupbar = {
			col = {
				active = "rgb(4385be)",
				inactive = "rgb(575653)",
				locked_active = "rgb(d14d41)",
				locked_inactive = "rgb(575653)",
			},
		},
	},
})
